---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: default
  annotations:
    # let metallb allocate a random IP
    # metallb.universe.tf/loadBalancerIPs: 172.16.1.20
spec:
  ports:
    # dont expose this port in a production TLS deployment - it exposes the plain client port
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
