- name: App setup
  hosts: all
  become: true
  become_user: ec2-user
  become_method: sudo
  tasks:
  - community.general.homebrew:
      name: golang,java,yq,jq,helm
      state: present
      update_homebrew: true
  - name: "CFSSL"
    # path seems to change randomly between intel/arm - rosetta?
    ansible.builtin.shell: |
      export PATH="{{ ansible_env.PATH }}:/usr/local/bin:/opt/homebrew/bin"
      go install github.com/cloudflare/cfssl/cmd/...@latest
  - name: "add GO installed binaries to path"
    ansible.builtin.lineinfile:
      path: /Users/ec2-user/.zshrc
      state: present
      regexp: '^export PATH='
      # ~/bin must be higher up path then confluent CLI to avoid using old CLI in SDK...
      # ZSH does not evaluate ~/ at login
      line: export PATH="/Users/ec2-user/bin:/Users/ec2-user/.bin:/Users/ec2-user/go/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/confluent/bin${PATH+:$PATH}"
  # https://stackoverflow.com/a/65601197
  - name: "symlink java"
    become: true
    become_user: root
    # Just do what the script says, -r probably needed and no option for this in ansible
    ansible.builtin.shell: |
      sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
