- name: App setup
  hosts: all
  become: true
  become_user: ec2-user
  become_method: sudo
  tasks:
  - community.general.homebrew:
      name: golang,java,yq,jq,confluentinc/tap/cli,helm
      state: present
      update_homebrew: true
  - name: "CFSSL"
    # path seems to change randomly between intel/arm - rosetta?
    ansible.builtin.shell: |
      export PATH="{{ ansible_env.PATH }}:/usr/local/bin:/opt/homebrew/bin"
      go install github.com/cloudflare/cfssl/cmd/...@latest

