- name: Docker setup
  hosts: all
  become: true
  become_user: ec2-user
  become_method: sudo
  tasks:
  - name: rosetta install
    ansible.builtin.shell: |
      softwareupdate --install-rosetta --agree-to-license
  - name: docker install
    ansible.builtin.shell: |
      curl -O "https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-arm64"
      sudo hdiutil attach Docker.dmg
      sudo /Volumes/Docker/Docker.app/Contents/MacOS/install --accept-license
